#pragma once

#include <cstdlib>
#include <utility>
#include <string>
#include <string_view>
#include <array>
#include <vector>
#include <deque>
#include <list>
#include <map>
#include <unordered_map>
#include <stack>
#include <functional>
#include <queue>
#include <iterator>
#include <algorithm>
#include <cmath>
#include <random>
#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <memory>
#include <optional>
#include <type_traits>
#include <typeindex>
#include <string>
#include <typeinfo>
#include <bitset>
#include <thread>
#include <mutex>
#include <shared_mutex>
#include <future>
#include <chrono>
#include <cassert>

// SFML
#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>

// EnTT
#include <EnTT/entt.h>

// Cereal
#include <cereal/cereal.hpp>
#include <cereal/archives/binary.hpp>
#include <cereal/archives/portable_binary.hpp>
#include <cereal/types/string.hpp>
#include <cereal/types/vector.hpp>
#include <cereal/types/unordered_set.hpp>
